//! The expression IR.

#[derive(Debug)]
pub enum Primitive {
    Unreachable,
    I32Eq,
    I32Ne,
    I32Eqz,
    I32LeU,
    I32LtU,
    I32GeU,
    I32GtU,
    I32LeS,
    I32LtS,
    I32GeS,
    I32GtS,
    I32Add,
    I32Sub,
    I32Mul,
    I32DivU,
    I32DivS,
    I32RemU,
    I32RemS,
    I32And,
    I32Or,
    I32Xor,
    I32Shl,
    I32ShrU,
    I32ShrS,
    I32Rotl,
    I32Rotr,
    I32Clz,
    I32Ctz,
    I32Popcnt,
    I32WrapI64,
    I32Extend8S,
    I32Extend16S,
    I32TruncF32U,
    I32TruncF32S,
    I32TruncF64U,
    I32TruncF64S,
    I32TruncSatF32U,
    I32TruncSatF32S,
    I32TruncSatF64U,
    I32TruncSatF64S,
    I32ReinterpretF32,
    I64Eq,
    I64Ne,
    I64Eqz,
    I64LeU,
    I64LtU,
    I64GeU,
    I64GtU,
    I64LeS,
    I64LtS,
    I64GeS,
    I64GtS,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivU,
    I64DivS,
    I64RemU,
    I64RemS,
    I64And,
    I64Or,
    I64Xor,
    I64Shl,
    I64ShrU,
    I64ShrS,
    I64Rotl,
    I64Rotr,
    I64Clz,
    I64Ctz,
    I64Popcnt,
    I64Extend8S,
    I64Extend16S,
    I64Extend32S,
    I64ExtendI32U,
    I64ExtendI32S,
    I64TruncF32U,
    I64TruncF32S,
    I64TruncF64U,
    I64TruncF64S,
    I64TruncSatF32U,
    I64TruncSatF32S,
    I64TruncSatF64U,
    I64TruncSatF64S,
    I64ReinterpretF64,
    F32Eq,
    F32Ne,
    F32Le,
    F32Lt,
    F32Ge,
    F32Gt,
    F32Add,
    F32Sub,
    F32Mul,
    F32Div,
    F32Abs,
    F32Neg,
    F32Sqrt,
    F32Floor,
    F32Ceil,
    F32Trunc,
    F32Nearest,
    F32Min,
    F32Max,
    F32Copysign,
    F32ConvertI32U,
    F32ConvertI32S,
    F32ConvertI64U,
    F32ConvertI64S,
    F32ReinterpretI32,
    F32DemoteF64,
    F64Eq,
    F64Ne,
    F64Le,
    F64Lt,
    F64Ge,
    F64Gt,
    F64Add,
    F64Sub,
    F64Mul,
    F64Div,
    F64Abs,
    F64Neg,
    F64Sqrt,
    F64Floor,
    F64Ceil,
    F64Trunc,
    F64Nearest,
    F64Min,
    F64Max,
    F64Copysign,
    F64ConvertI32U,
    F64ConvertI32S,
    F64ConvertI64U,
    F64ConvertI64S,
    F64ReinterpretI64,
    F64PromoteF32,
}

#[derive(Debug)]
pub enum Expr {
    Const(String),
    Global(usize),
    GlobalSet(usize, Box<Expr>),
    Local(String),
    Setf(String, Box<Expr>),
    Call(String, Vec<Expr>),
    CallIndirect(Box<Expr>, Vec<Expr>),
    If(Box<Expr>, Box<Expr>, Box<Expr>),
    Select(Box<Expr>, Box<Expr>, Box<Expr>),
    Progn(Vec<Expr>),
    Prog1(Box<Expr>, Vec<Expr>),
    Prim(Primitive, Vec<Expr>),
    Block(String, Box<Expr>),
    ReturnFrom(String, Box<Expr>),
    Tagbody(String, Box<Expr>),
    Go(String),
    Switch(Box<Expr>, Box<Expr>, Vec<Expr>),
    I32Load(Option<(usize, bool)>, Box<Expr>, usize),
    I32Store(Option<usize>, Box<Expr>, Box<Expr>, usize),
    I64Load(Option<(usize, bool)>, Box<Expr>, usize),
    I64Store(Option<usize>, Box<Expr>, Box<Expr>, usize),
    F32Load(Box<Expr>, usize),
    F32Store(Box<Expr>, Box<Expr>, usize),
    F64Load(Box<Expr>, usize),
    F64Store(Box<Expr>, Box<Expr>, usize),
    Try {
        name: String,
        body: Box<Expr>,
        handlers: Vec<CatchHandler>,
    },
    Throw(usize, Vec<Expr>),
    Rethrow(String),
    ThrowRef(Box<Expr>),
    Values(Vec<Expr>),
    SetfValues {
        locals: Vec<String>,
        value: Box<Expr>,
    },
}

#[derive(Debug)]
pub struct CatchHandler {
    pub tag: Option<u32>,
    pub vars: Vec<String>,
    pub exnref_var: Option<String>,
    pub body: Box<Expr>,
}

impl Expr {
    pub fn fused_pred(&self) -> Option<(&'static str, &[Expr])> {
        match self {
            Expr::Prim(Primitive::I32Eqz, args) => Some(("i32eqz.fused", args)),
            Expr::Prim(Primitive::I32Eq, args) => Some(("i32eq.fused", args)),
            Expr::Prim(Primitive::I32Ne, args) => Some(("i32ne.fused", args)),
            Expr::Prim(Primitive::I32LeU, args) => Some(("i32leu.fused", args)),
            Expr::Prim(Primitive::I32LtU, args) => Some(("i32ltu.fused", args)),
            Expr::Prim(Primitive::I32GeU, args) => Some(("i32geu.fused", args)),
            Expr::Prim(Primitive::I32GtU, args) => Some(("i32gtu.fused", args)),
            Expr::Prim(Primitive::I32LeS, args) => Some(("i32les.fused", args)),
            Expr::Prim(Primitive::I32LtS, args) => Some(("i32lts.fused", args)),
            Expr::Prim(Primitive::I32GeS, args) => Some(("i32ges.fused", args)),
            Expr::Prim(Primitive::I32GtS, args) => Some(("i32gts.fused", args)),
            Expr::Prim(Primitive::I64Eqz, args) => Some(("i64eqz.fused", args)),
            Expr::Prim(Primitive::I64Eq, args) => Some(("i64eq.fused", args)),
            Expr::Prim(Primitive::I64Ne, args) => Some(("i64ne.fused", args)),
            Expr::Prim(Primitive::I64LeU, args) => Some(("i64leu.fused", args)),
            Expr::Prim(Primitive::I64LtU, args) => Some(("i64ltu.fused", args)),
            Expr::Prim(Primitive::I64GeU, args) => Some(("i64geu.fused", args)),
            Expr::Prim(Primitive::I64GtU, args) => Some(("i64gtu.fused", args)),
            Expr::Prim(Primitive::I64LeS, args) => Some(("i64les.fused", args)),
            Expr::Prim(Primitive::I64LtS, args) => Some(("i64lts.fused", args)),
            Expr::Prim(Primitive::I64GeS, args) => Some(("i64ges.fused", args)),
            Expr::Prim(Primitive::I64GtS, args) => Some(("i64gts.fused", args)),
            Expr::Prim(Primitive::F32Eq, args) => Some(("f32eq.fused", args)),
            Expr::Prim(Primitive::F32Ne, args) => Some(("f32ne.fused", args)),
            Expr::Prim(Primitive::F32Le, args) => Some(("f32le.fused", args)),
            Expr::Prim(Primitive::F32Lt, args) => Some(("f32lt.fused", args)),
            Expr::Prim(Primitive::F32Ge, args) => Some(("f32ge.fused", args)),
            Expr::Prim(Primitive::F32Gt, args) => Some(("f32gt.fused", args)),
            Expr::Prim(Primitive::F64Eq, args) => Some(("f64eq.fused", args)),
            Expr::Prim(Primitive::F64Ne, args) => Some(("f64ne.fused", args)),
            Expr::Prim(Primitive::F64Le, args) => Some(("f64le.fused", args)),
            Expr::Prim(Primitive::F64Lt, args) => Some(("f64lt.fused", args)),
            Expr::Prim(Primitive::F64Ge, args) => Some(("f64ge.fused", args)),
            Expr::Prim(Primitive::F64Gt, args) => Some(("f64gt.fused", args)),
            _ => None,
        }
    }
}
